name: build
on:
  push:
    branches: 
      - main # 仅在主分支上触发
    tags: # 仅在推送标签时触发工作流
      - "v*" # 只匹配以 "v" 开头的标签，例如 v1.0.0, v2.1.3

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v4

      - name: 安装node环境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: 获取pnpm仓库目录
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: 设置pnpm缓存
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 安装Python3环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"

      - name: 初始化打包环境
        run: pnpm run init

      - name: 开始打包
        run: pnpm run build

      # 上传到 GitHub Actions 的构建工件（artifact）存储中，并不会自动推送到 GitHub Releases。
      - name: 上传打包完成的程序包
        uses: actions/upload-artifact@v4
        with:
          name: Setup_${{ runner.os }}
          retention-days: 1
          path: build/*-*_*.*

      # 创建 GitHub Release
      - name: 创建 GitHub Release
        uses: actions/create-release@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            这里是版本发布说明，描述此版本的更新内容。
          draft: false
          prerelease: false
          token: ${{ secrets.kgnix_github_token }} # 使用 GitHub 自动提供的 token

      # 上传 Windows .exe 文件(zip压缩后)到 Release
      - name: 上传 Windows .exe 文件(zip压缩后)到 Release
        uses: actions/upload-release-asset@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/Setup_Windows.zip  # 假设打包后的 zip 文件路径
          asset_name: kgnix-windows-${{ github.ref }}.zip  # 上传时的文件名称，格式为 kgnix-windows-v1.0.0.zip
          asset_content_type: application/zip  # 这里的 MIME 类型应为 application/zip
          token: ${{ secrets.kgnix_github_token }} # 自动使用 GitHub token 自定义创建的 kgnix_github_token

      # 上传 macOS .dmg 文件(zip压缩后)到 Release
      - name: 上传 macOS .dmg 文件(zip压缩后)到 Release
        uses: actions/upload-release-asset@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/Setup_macOS.zip  # 假设打包后的 zip 文件路径
          asset_name: kgnix-macos-${{ github.ref }}.zip  # 上传时的文件名称，格式为 kgnix-macos-v1.0.0.zip
          asset_content_type: application/zip  # 这里的 MIME 类型应为 application/zip
          token: ${{ secrets.kgnix_github_token }} # 自动使用 GitHub token 自定义创建的 kgnix_github_token

      # 上传 Linux .deb 文件(zip压缩后)到 Release
      - name: 上传 Linux .deb 文件(zip压缩后)到 Release
        uses: actions/upload-release-asset@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/Setup_Linux.zip  # 假设打包后的 zip 文件路径
          asset_name: kgnix-linux-${{ github.ref }}.zip  # 上传时的文件名称，格式为 kgnix-linux-v1.0.0.zip
          asset_content_type: application/zip  # 这里的 MIME 类型应为 application/zip
          token: ${{ secrets.kgnix_github_token }} # 自动使用 GitHub token 自定义创建的 kgnix_github_token
